apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: prometheus-1
    orgId: 1

prune: true

datasources:
  - name: Prometheus
    uid: prometheus-local
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
