from __future__ import annotations

from datetime import datetime
from typing import Protocol


class NoticeRepository(Protocol):
    def create_notice(self, title: str, content: str) -> dict: ...
    def list_notices(self, page: int, size: int) -> tuple[list[dict], int]: ...
    def get_notice(self, notice_id: int) -> dict | None: ...
    def update_notice(self, notice_id: int, title: str | None, content: str | None) -> dict | None: ...
    def delete_notice(self, notice_id: int) -> dict | None: ...


class EmailAuthRepository(Protocol):
    def issue_email_code(self, email: str, code: str = "123456", ttl_minutes: int = 5) -> None: ...
    def verify_email_code(self, email: str, code: str) -> bool: ...
    def require_verified_email(self, email: str) -> bool: ...
    def get_credit(self, email: str) -> dict: ...
    def require_credit(self, email: str) -> bool: ...
    def consume_credit(self, email: str) -> dict: ...


class SessionRepository(Protocol):
    def issue_session(self, email: str, minutes: int) -> dict: ...
    def extend_session(self, session_id: str, minutes: int) -> dict | None: ...


class PopupRepository(Protocol):
    popup: dict | None


class AppRepository(NoticeRepository, EmailAuthRepository, SessionRepository, PopupRepository, Protocol):
    def reset(self) -> None: ...


def isoformat_utc(value: datetime) -> str:
    return value.replace(microsecond=0).isoformat()
